# Generated by Django 4.1.1 on 2022-09-09 02:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppPerfil', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Titulo',
            new_name='titulo',
        ),
        migrations.AddField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
